apiVersion: stackpulse.io/v1
kind: Step
metadata:
  version: 1.0.0
  name: "json_parser"
  description: "Parse given raw data as JSON and output it directly to the context. This allows using generic docker images which output JSON (like aws cli for example) and to be able to operate on their output in the playbooks context. "
  vendor: custom
  type: custom

envs:
  - name: INPUT
    description: "Input to parse. If not provided, the parser will use the previous step output as input."
    type: string
  - name: DEBUG
    type: bool
    description: "Debug mode. Print debug information to stdout."
    example: false

outputs:
  - name: output
    description: "The output will contain the parsed input json."
    type: json
