apiVersion: stackpulse.io/v1
kind: Step
metadata:
  name: "gcloud_cmd"
  description: "Generic Gcloud CLI command"
  vendor: gcp
  type: advanced
  version: 1.0.0

envs:
  - name: COMMAND
    description: "Gcloud specific command."
    type: "string"
    required: true
    
outputs:
  - name: output
    description: "The Gcloud CLI command result. The format depends on the specific command."
    type: string