apiVersion: stackpulse.io/v1
kind: Step
metadata:
  version: 1.0.0
  name: "get_ips_for_instances"
  description: "Get private ips for given ec2 instances."
  vendor: aws
  type: triage

envs:
  - name: INSTANCE_IDS
    description: "Instance IDs to get the ips for. Max instances allowed - 1000."
    type: "json"
    required: true
    example: '["i-04cd3e5a680ce947c", "i-0673fbea5ed878416"]'
  - name: REGION
    description: "Instances aws region."
    type: "string"
    required: true
    example: "us-west-2"

outputs:
  - name: ips
    description: "JSON array contains the ips for the given instances"
    type: "json"
    example: '["192.168.77.111", "192.168.66.189"]'

integrations:
  - aws