apiVersion: stackpulse.io/v1
kind: Step
metadata:
  version: 1.0.0
  name: "aws_attach_volume"
  description: "Attach AWS volume to AWS instance."
  vendor: aws
  type: remediation

args:
  - name: command
    description: "AWS specific command."
    type: "string"
    required: true
    default: "ec2"
  - name: subcommand
    description: "AWS subcommand."
    type: "string"
    required: true
    default: "attach-volume"
  - name: --volume-id
    description: "The ID of the volume."
    required: true
    type: "string"
    default: "{{ .volumeID }}"
  - name: --instance-id
    description: "Instance ID to attach."
    type: "string"
    required: true
    default: "{{ .instanceID }}"
  - name: --device
    description: "device name to use"
    type: "string"
    required: true
    default: "/dev/sdf"

outputs:
  - name: AttachTime
    description: "The time stamp when the attachment initiated."
    type: string
    example: 2021-03-30T21:01:05.123Z
  - name: InstanceId
    description: "The ID of the instance."
    type: string
    example: i-01474ef662b89480
  - name: VolumeId
    description: "The ID of the volume."
    type: string
    example: vol-1234567890abcdef0
  - name: State
    description: "The attachment state of the volume."
    type: string
    example: attaching
  - name: Device
    description: "The device name."
    type: string
    example: /dev/sdf

integrations:
  - aws
